---
title: "QTM302W Methods Section"
author: "Isabella Adeola, Hank Standaert, Christina Dai"
date: "2025-11-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(kableExtra)
```

```{r}
ciri_data <- read_csv("data/dataverse_files/CIRI Data 1981_2011 2014.04.14.csv") 

#Removing unnecessary variables from data set
df <- ciri_data %>% 
  select(-c(DISAP,
            UNCTRY,
            CIRI,
            KILL, 
            POLPRIS,
            COW, 
            TORT,
            UNSUBREG, 
            POLITY,
            OLD_EMPINX,
            NEW_EMPINX,
            ASSN,
            FORMOV,
            DOMMOV,
            OLD_MOVE,
            SPEECH,
            ELECSD,
            OLD_RELFRE,
            NEW_RELFRE,
            WORKER,
            WOSOC,
            INJUD)) 
```


```{r}
# Checking for number of NA's in each variable and deleting rows with NA's
print(colSums(is.na(df))) 
df_full <- na.omit(df) 

# Checking for duplicates within variables and duplicate rows
print(sum(duplicated(df_full))) 
df_no_dups <- distinct(df_full) 

```

```{r}
# Making missing code, periods of interregnum, and occupation NAs
df_no_dups[df_no_dups == -999] <- NA
df_no_dups[df_no_dups == -77]  <- NA
df_no_dups[df_no_dups == -66]  <- NA

# Creating decade variable 
df_decade_region <- df_no_dups %>% 
  mutate(DECADE = floor(YEAR/10)*10)

# Map UNREG codes to continent/region names
region_map <- tibble(
  UNREG = c(2, 9, 419, 21, 142, 150),
  CONT = c("Africa", "Oceania", "South & Central America", "North America" , "Asia", "Europe") 
) 

# Combining the two tables
df_decade_region <- df_decade_region %>%
  left_join(region_map, by = "UNREG")

# Getting rid of duplicate column and renaming `CONT.x`
df_decade_region$CONT.y <- NULL

names(df_decade_region)[names(df_decade_region) == "CONT.x"] <- "CONT"

df_decade_region
```

```{r}
# Creating data frame for just Africa
df_africa <- df_decade_region %>% 
  filter(CONT == 'Africa')

head(df_africa)
```


```{r}
# Creating data frame for just continental countries
island_list <- c("Madagascar", "Comoros",
         "Mauritius", "Seychelles", "Cape Verde", "Sao Tome and Principe")

df_africa_cont <- df_africa %>% 
  filter(CTRY != island_list)

head(df_africa_cont)
```
```{r}
# Creating data frame for just African island nations
df_islands <- df_africa %>%
  filter(CTRY == island_list)

head(df_islands)
```
```{r}
# Reading new data set 
africa_popgdp <- read_csv("data/africa_popgdp.csv") 

head(africa_popgdp)
```

```{r}
africa_cont_joined <- df_africa_cont %>% 
  left_join(africa_popgdp, by = c("CTRY", "YEAR")) %>%
   group_by(DECADE) %>%
  fill(AREA, URBPOP, TPOP, GDP, .direction = "downup") %>%
  ungroup()

head(africa_cont_joined)
```

```{r}
islands_joined <- df_islands %>% 
  left_join(africa_popgdp, by = c("CTRY", "YEAR")) %>%
   group_by(DECADE) %>%
  fill(AREA, URBPOP, TPOP, GDP, .direction = "downup") %>%
  ungroup()

head(islands_joined)
```

After reviewing the data set for our island_joined information, we chose to only keep the data after 2000 since any data that was before that year was missing/ full of NAs. 
```{r}
island_join_clean <- na.omit(islands_joined)

summary_df <- island_join_clean %>%
  group_by(CTRY) %>%
  summarize(
    mean_WECON = mean(WECON, na.rm = TRUE)
  )

ggplot(summary_df,
       aes(x = CTRY, y = mean_WECON)) +
  geom_bar(stat = "identity", fill = "lightpink") +
  facet_wrap(~ CTRY, scales = "free_x") +
  labs(
    x = "Island Country",
    y = "Average WECON Score"
  ) +
  theme_minimal() 
```

